[project]
name = "pypebbles"
version = "0.2.4"
description = "Python Pebbles"
authors = [
    {name = "Mike Pebbles", email = "mq.pebbles@gmail.com"}
]
readme = "README.md"
dynamic = ["dependencies"]
requires-python = ">=3.12,<4"

[tool.poetry.dependencies]
httpx2 = "*"

[tool.poetry.group.dev.dependencies]
apexcodexpy = "0.7.1"
faker = "*"
pytest = "*"
pytest-cov = "*"
pytest-recording = "*"
hypothesis = "^6.168.0"

[tool.mypy]
strict = true
ignore_missing_imports = true
show_error_codes = true
pretty = true

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "B",
    "C4",
    "PT",
    "RSE",
    "RET",
    "SIM",
    "T20",
    "E",
    "W",
    "F",
    "I",
    "N",
    "UP",
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.coverage.run]
branch = true
source = [
    "pypebbles",
    "tests",
]

[tool.coverage.report]
skip_empty = true
skip_covered = true
show_missing = true
