name: Validate Python Code
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout Code
        uses: actions/checkout@v7
      - &python
        name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - &codex
        name: Install Codex
        shell: bash
        run: pip install apexcodexpy==0.6.6
      - name: Lint Code
        run: codex lint --ci
  test-unit:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - *checkout
      - *python
      - *codex
      - name: Run unit tests
        run: codex test unit --ci


